### ISSUE TITLE
increase-temp and decrease-temp work opposite

### ISSUE THREAD

**Issue by liljenstolpe** [juliusv/elgato-key-light-controller#1]
Greetings,

For some insane reason, Elgato decided to encode the hottest temp (9000K) as 143, and the coolest (2900K) as 344. 

Therefore, when you try and 'raise-temp' you will actually lower the temp with your code, and if it is already at the coolest (2900K), you won't raise it at all (it can't go lower).  Same if you are trying to "lower" when you are at 9000K.

You actually need to invert the directions in your script.  I will be doing a bit of work here, so I can do a PR in a little bit.

Also, do you want to continue to use the integer numbers for temp as per the Elgato API, or do you want to use K (which more people will grok)?  If so, I can pull over the conversion code that is in the legato python code which should give the ability to input colors as temps, rather than 'semi random' integers.

**Comment by juliusv** [comment]
Hi @liljenstolpe, oh right, thanks for that :) I just pushed a commit to reverse the temperature directions. I'm totally fine with a contribution around Kelvin if you like, although the way I use the tool (just pressing "increase temp" and "decrease temp" keys on my keyboard) I would never interact with a specific color in K directly, so integers were actually more convenient.

Btw. after hacking this tool together in about an hour, I learned about https://github.com/endocrimes/keylightctl, which looks like a much much more proper CLI tool for controlling Elgato Key Lights... so maybe that is interesting!
